INITIAL_PROMPT = """
Pythonを使って数学の問題を解いてみましょう。

クエリ要件：
常に出力には'print'関数を使用し、少数ではなく分数や混合形式を使用してください。
sympyなどのパッケージを利用しても構いません。
以下のフォーマットに従ってコードを書いてください。

```python
{{LLMエージェントにより出力されたPythonのコード}}
```

まず、問題を解くための主な考え方を述べてください。問題を解くためには以下の3つの方法から選択できます：
Case1：問題が直接Pythonのコードで解決できる場合、プログラムを書いて解決してください。必要に応じてすべての可能な配置を列挙しても構いません。
Case2：問題が主に推論で解決できる場合、自分で直接解決してください。
Case3：上記の２つの方法で対処できない場合、次のプロセスに従ってください：
1. 問題をステップバイステップで解決する(ステップを過度に細分化しないでください)。
2. Pythonを使って問い合わせることができるクエリ(計算や方程式など)を取り出します。
3. 結果を私に教えてください。
4. 結果が正しいと思う場合は実行してください。結果が無効または予期しない場合は、クエリまたは推論を修正してください。

すべてのクエリが実行され、答えを得た後、答えを\\boxed{{}}に入れてください。
\\boxed{{}}の有無で答えが出たかを判定しています。最終的な答えが出たとき以外は、\\boxed{{}}を使用しないでください。
応答が得られた場合は、シンプルに表示してください。追加の出力などはしないでください。

問題文：{problem}
"""
problem = """
問題：偽の金塊は、コンクリートの立方体を金色のペイントで覆うことによって作られています。
ペイントのコストは立方体の表面積に比例し、コンクリートのコストは体積に比例します。
1センチの立方体を作るコストは130円であり、2センチの立方体を作るコストが680円であるとき、3センチの立方体を作るコストはいくらになりますか？
"""
